name: grafana_elements
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - loki
  loki:
    container_name: loki
    image: grafana/loki
    ports:
      - '3100:3100'
    depends_on:
      - promtail
  promtail:
    container_name: promtail
    image: grafana/promtail
    volumes:
      - ./logs/:/var/log/